services:
  - type: web
    name: tramite-backend
    runtime: php
    repo: https://github.com/avoca2/tramite-documentario
    plan: free
    rootDir: backend-laravel
    buildCommand: composer install --no-dev && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d9f3f36rnols73fbkrrg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: iestp_tramites
      - key: DB_USERNAME
        value: iestp_tramites_user
      - key: DB_PASSWORD
        sync: false

databases:
  - name: tramite-db
    databaseName: iestp_tramites
    user: iestp_tramites_user
    plan: free
